### ISSUE TITLE
physical-chemistry-(iiith)-lab_nuclear-magnetic-resosnace-spectrocopy-and-evaulation-of-simple-1h-nmr-spectra-of-select-organic-compounds_experiment

### ISSUE THREAD

**Issue by gayatripurigilla** [virtual-labs/physical-chemistry-iiith#19]
Defect description : when clicked on the 'click here' option in the experiment it is popping up a message down at the bottom that the type of file is harmful to the computer.steps to reproduce issue:1.click on physical chemistry lab.2.select list of experiments.3.click on the experiment nuclear magnetic resosnace spectrocopy and evaulation of simple 1h nmr spectra of select organic compounds.4.select experiment .5.click on 'click here' option .expected result : the experiment should not cause any harm to the computer.actual result : a pop message that the type of file is harmful is displayed at the bottom.environment :  *  os-windows 8.1  *  hardware configuration: 8 gb ram  *  processor :i5  *  browser : google chromeattachments:![image](https://gitlab.com/vishwanathamsarika/virtual-labs-internship-sarika/uploads/f7863e56fda72d4cefb26adf90fd1aff/image.png)

**Comment by SaiKrishnaReddy644** [comment]
fixed it f30a666

**Comment by VishwanathamSarika** [comment]
The same pop up is coming , i think the issue is not fixed yet 

![image1](https://user-images.githubusercontent.com/39979596/41705299-37c97b50-7556-11e8-8eff-86eb29e84cdf.png)

**Comment by SaiKrishnaReddy644** [comment]
Ok I will see about it

**Comment by SaiKrishnaReddy644** [comment]
fix id f408924ac16c9a80d1966a05580baec32795f9b4

**Comment by VishwanathamSarika** [comment]
The issue is fixed now .

**Comment by varshareddykumbham** [comment]
Valid fix

**Comment by Uppala-Kalanandini** [comment]
COMMIT ID: 88b2b56   0274fab

**Comment by Gowthambhujam** [comment]
Valid fix @Uppala-Kalanandini
